apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: search
  name: search
spec:
  host: online-new.alinma.com
  path: /api/channel-search
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: search
