apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: emarket
  name: emarket
spec:
  host: online-new.alinma.com
  path: /retail/emarket
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: emarket
