apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: customers
  name: customers
spec:
  host: online-new.alinma.com
  path: /retail/customer-management
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: customers
