apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: admin
  name: admin
spec:
  host: online-new.alinma.com
  path: /api/administration
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: admin
