apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: investment
  name: investment
spec:
  host: online-new.alinma.com
  path: /retail/investment
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: investment
