apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: finance
  name: finance
spec:
  host: online-new.alinma.com
  path: /retail/finance-management
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: finance
