apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: atm
  name: atm
spec:
  host: online-new.alinma.com
  path: /retail/atm-management
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: atm
