apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 300s
  labels:
    app: dvs-portal
  name: dvs-portal
spec:
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: dvs-portal
