apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: pfm
  name: pfm
spec:
  host: online-new.alinma.com
  path: /retail/pfm
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: pfm
