apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: micro-site
  name: micro-site
spec:
  host: m.alinma.com
  port:
    targetPort: http
  tls:
    caCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIEyDCCA7CgAwIBAgIQDPW9BitWAvR6uFAsI8zwZjANBgkqhkiG9w0BAQsFADBh
      MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
      d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBH
      MjAeFw0yMTAzMzAwMDAwMDBaFw0zMTAzMjkyMzU5NTlaMFkxCzAJBgNVBAYTAlVT
      MRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxMzAxBgNVBAMTKkRpZ2lDZXJ0IEdsb2Jh
      bCBHMiBUTFMgUlNBIFNIQTI1NiAyMDIwIENBMTCCASIwDQYJKoZIhvcNAQEBBQAD
      ggEPADCCAQoCggEBAMz3EGJPprtjb+2QUlbFbSd7ehJWivH0+dbn4Y+9lavyYEEV
      cNsSAPonCrVXOFt9slGTcZUOakGUWzUb+nv6u8W+JDD+Vu/E832X4xT1FE3LpxDy
      FuqrIvAxIhFhaZAmunjZlx/jfWardUSVc8is/+9dCopZQ+GssjoP80j812s3wWPc
      3kbW20X+fSP9kOhRBx5Ro1/tSUZUfyyIxfQTnJcVPAPooTncaQwywa8WV0yUR0J8
      osicfebUTVSvQpmowQTCd5zWSOTOEeAqgJnwQ3DPP3Zr0UxJqyRewg2C/Uaoq2yT
      zGJSQnWS+Jr6Xl6ysGHlHx+5fwmY6D36g39HaaECAwEAAaOCAYIwggF+MBIGA1Ud
      EwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFHSFgMBmx9833s+9KTeqAx2+7c0XMB8G
      A1UdIwQYMBaAFE4iVCAYlebjbuYP+vq5Eu0GF485MA4GA1UdDwEB/wQEAwIBhjAd
      BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwdgYIKwYBBQUHAQEEajBoMCQG
      CCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wQAYIKwYBBQUHMAKG
      NGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbFJvb3RH
      Mi5jcnQwQgYDVR0fBDswOTA3oDWgM4YxaHR0cDovL2NybDMuZGlnaWNlcnQuY29t
      L0RpZ2lDZXJ0R2xvYmFsUm9vdEcyLmNybDA9BgNVHSAENjA0MAsGCWCGSAGG/WwC
      ATAHBgVngQwBATAIBgZngQwBAgEwCAYGZ4EMAQICMAgGBmeBDAECAzANBgkqhkiG
      9w0BAQsFAAOCAQEAkPFwyyiXaZd8dP3A+iZ7U6utzWX9upwGnIrXWkOH7U1MVl+t
      wcW1BSAuWdH/SvWgKtiwla3JLko716f2b4gp/DA/JIS7w7d7kwcsr4drdjPtAFVS
      slme5LnQ89/nD/7d+MS5EHKBCQRfz5eeLjJ1js+aWNJXMX43AYGyZm0pGrFmCW3R
      bpD0ufovARTFXFZkAdl9h6g4U5+LXUZtXMYnhIHUfoyMo5tS58aI7Dd8KvvwVVo4
      chDYABPPTHPbqjc1qCmBaZx2vN4Ye5DUys/vZwP9BFohFrH/6j/f3IL16/RZkiMN
      JCqVJUzKoZHm1Lesh3Sz8W2jmdv51b2EQJ8HmA==
      -----END CERTIFICATE-----
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIGuTCCBaGgAwIBAgIQBxZHhJNt451nKnyppZ9KEDANBgkqhkiG9w0BAQsFADBZ
      MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMTMwMQYDVQQDEypE
      aWdpQ2VydCBHbG9iYWwgRzIgVExTIFJTQSBTSEEyNTYgMjAyMCBDQTEwHhcNMjQw
      NzA4MDAwMDAwWhcNMjUwNzA3MjM1OTU5WjBLMQswCQYDVQQGEwJTQTEPMA0GA1UE
      BxMGUml5YWRoMRQwEgYDVQQKEwtBbGlubWEgQmFuazEVMBMGA1UEAxMMbS5hbGlu
      bWEuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAorDvt1kFCDub
      4dLCeuH7qDHuQVyM0layvjSvIUaa2NXw6FwKb46AOsuXfYDLeFByB8eJ9AvDG1zC
      eR6xBDGR9qI0RY/isi2kPpe4SBxnONtuiCyEAXuoeXtRkqQr4uklMriPYSfOfRMp
      Y8cyKbo8tRiahXdaunWNsq2hAvt93KpZZKea8w57/wdNZ9aDow+JG09XMKQTTtT9
      CfNn0oBzonIm8AX/F9DcxIlxTQ7QPQvnFfn1hIiyJ0mJ1mRzxxwBJzLIHlUEo4cP
      zWXqNQVp4n+7Sg/EpF4gCZGb27vXrXmvh93IQZyWeqOroWknao8Ln8rSSyXwj/Vm
      ijvjtsvhmwIDAQABo4IDiTCCA4UwHwYDVR0jBBgwFoAUdIWAwGbH3zfez70pN6oD
      Hb7tzRcwHQYDVR0OBBYEFLhlZxDWUvPAzk6UMHa6U4w93nerMBcGA1UdEQQQMA6C
      DG0uYWxpbm1hLmNvbTA+BgNVHSAENzA1MDMGBmeBDAECAjApMCcGCCsGAQUFBwIB
      FhtodHRwOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMwDgYDVR0PAQH/BAQDAgWgMB0G
      A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjCBnwYDVR0fBIGXMIGUMEigRqBE
      hkJodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRHbG9iYWxHMlRMU1JT
      QVNIQTI1NjIwMjBDQTEtMS5jcmwwSKBGoESGQmh0dHA6Ly9jcmw0LmRpZ2ljZXJ0
      LmNvbS9EaWdpQ2VydEdsb2JhbEcyVExTUlNBU0hBMjU2MjAyMENBMS0xLmNybDCB
      hwYIKwYBBQUHAQEEezB5MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2Vy
      dC5jb20wUQYIKwYBBQUHMAKGRWh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9E
      aWdpQ2VydEdsb2JhbEcyVExTUlNBU0hBMjU2MjAyMENBMS0xLmNydDAMBgNVHRMB
      Af8EAjAAMIIBfwYKKwYBBAHWeQIEAgSCAW8EggFrAWkAdgAS8U40vVNyTIQGGcOP
      P3oT+Oe1YoeInG0wBYTr5YYmOgAAAZCSfJ8lAAAEAwBHMEUCIEs9HSRZxkxkM/+p
      FbWctuY5ZmgUnThZbBF9MfOx/3gZAiEAuxx2HcNnGHzeE2G9Ngavo+LHZ/Ktcx6w
      2+Ja00YlD1EAdwB9WR4S4XgqexxhZ3xe/fjQh1wUoE6VnrkDL9kOjC55uAAAAZCS
      fJ8iAAAEAwBIMEYCIQDbAKIOzynKJdbsH9BeeKQBav/8Qi6+1qW1RpF1udQrHQIh
      AOOCfnUCmIAk/ml6LBddIcFXOKxVx9YaurWv4OpSf+uNAHYA5tIxY0B3jMEQQQbX
      cbnOwdJA9paEhvu6hzId/R43jlAAAAGQknyfOwAABAMARzBFAiAWU10YkjvdWtcX
      xqLBwQBTT6Utz5TrZUpuXvgdJ5lX+wIhAIbO+EEWvFjiGPAaKqQ2EXA4OwVpMFAa
      qkCSkt0D0ZsgMA0GCSqGSIb3DQEBCwUAA4IBAQCkTWoMLwV5VxnLMDJcwCm2wVsf
      1vLBI+SdyBTLEeUME1XrrS0V+mhSPyv6yyCyniXS2PpsLG0hyLiQ/sUX5181LdXI
      dQal52BXikyNnDGUiI6aBLuZ76KQT084BV7nRF70FdPipnHDfrpG4J+k0A4tfKan
      yMOwOOF6bDtO76w2YRwzh+czGQYoNYdtCXa47Pp1EISc+NGjX0TQb0gw6Nl8IoQB
      wInWLMLMqfy2N0YjeS8zu6bUjnn4fs5F086AN28pFLr6FkjxKvTed/dtmwCnkctN
      RvS60gBZZKzdzCAb74qYYZwySnG9Z0Jts7iTUaJlXGISnR4xD40jPmrnT3wW
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCisO+3WQUIO5vh
      0sJ64fuoMe5BXIzSVrK+NK8hRprY1fDoXApvjoA6y5d9gMt4UHIHx4n0C8MbXMJ5
      HrEEMZH2ojRFj+KyLaQ+l7hIHGc4226ILIQBe6h5e1GSpCvi6SUyuI9hJ859Eylj
      xzIpujy1GJqFd1q6dY2yraEC+33cqllkp5rzDnv/B01n1oOjD4kbT1cwpBNO1P0J
      82fSgHOicibwBf8X0NzEiXFNDtA9C+cV+fWEiLInSYnWZHPHHAEnMsgeVQSjhw/N
      Zeo1BWnif7tKD8SkXiAJkZvbu9etea+H3chBnJZ6o6uhaSdqjwufytJLJfCP9WaK
      O+O2y+GbAgMBAAECggEAFj2uEm30XChvVQiPrGY8axqjAa3PVT9OTDu+PVmo+D+3
      IWzZGGBuHfDl6DMKneC8K11spJT/D+c3HCvFSKzQ0YYMiKifoHrQ21Bj0afgYfYi
      6YbRvQoqAVbfKKGSRlZXztP1oJ3lLVVzRmqy7DVuRdZJOY8UM4K346y3jZrSnVnh
      3KRJlmxtHy2bEaGRzAWeoKQNBeW6Xu5OJGMBBBQBe3qfkhsj0kFJPodaBtd3YQ1p
      mMi78PY+86aZm0weNmu88JNH4TCwHZFDkVvqs8Fhz4lIFt7W5GbsQxbW5o/KypUi
      qo0C1+DOp9uHlio6rqNO8Bj1ezshdRjZ+koo78SYoQKBgQDYn7ACWflzqjxcN5Q7
      rz9lfvcSU8eX8gt07LBBOPp9Yyv9LEyGjzNqj7QEssp+pu6+Q30QBY0rx9MY/bsM
      T8t6u+2cQfoKIrsx1f6KMMTBN6yrHyCREkY8OnkzUCdyqtin25eXBhs/EF9vpolx
      KBbyMdNZgFEx8ORFynmEsMdRAwKBgQDAQ5ATusxuPF7Bb3ID5uBZrvlz1tH/S9o1
      AKzQVXNwk2Q/6rKTwMJNH4n0gw+CKmg2kevWHPNpl78O0qtN1GiaLtchj5JRF71W
      mu96itAD56yJo5o/4QTNhXB47OtkFdBBRGPUtHUihBd8JVbliJujTe3dNqGPKegQ
      yp0AAkwtiQKBgQDWZV3PRfuk5YTuBDgaxjzpmDqykebGVNHP/H4JX3pTZTbhUNnA
      h7RssCOMTuQpa9B40NTTaZsqDJC6eE2LRuJt69ekwovVQkChd1mArfnd/dtQVfNm
      gX6wF3NjPN5+F+dsYuLqnymSRgMevuXi77meJYA3Yc96rR9Qj6+ri0cJvwKBgG6H
      aNCu1s+YzTCPDRDJLbjhKm851EfcJ3nJBZBPT6osUbmdB0SB0DHeK8Txg3zlPDwC
      732L7zOJFUFEQ07fCbN5shuNGiScbTDYqUvdeXCFQ19tOkP27HfqeppKOZi0IaEj
      2/BwPda18XphTO9v9WmQZ2qA+agAA3WDxXY32+thAoGBAKBKCvC3XpkKGL5dIFSK
      Cpr7aW+a6j5f0cVUvmH7UeG5AED6ZtjOYwcMz4nuXEDYoSGQxRdcD31QoJ75wQWK
      qHGZoWtOqYQjYgPHDN5ezIeh2iWJmVI8GokDT+odxHVcVmnDO4NT+zZi2FsWIeJB
      bq6gZ/W4LVgu1nPXfcgQ8mfP
      -----END PRIVATE KEY-----
    termination: edge
  to:
    kind: Service
    name: micro-site
